[package]
name = "rocksalt"
version = "0.1.0"
authors = ["mbuscemi <matthew.buscemi@gmail.com>"]
edition = "2018"

[dependencies]
web-view = { version = "0.6.2" }
ignore = "0.4.14"
rustc-serialize = "0.3.24"
serde = "1.0.106"
serde_json = "1.0.51"
serde_derive = "1.0.106"
tinyfiledialogs = "3.3.9"
